# Configuration file for License Visualizations
title: License Visualizations
author: Ruchita Alate
author_email: ralate2@illinois.edu
visualizations:
  - title: License Types by State
    type: bar_chart
    description: "This bar chart visualizes the distribution of license types across different states."
    color_scheme: categorical
    data_transformation: 
      filter: "State Selection"
      aggregate: "Count of Licenses by License Type"
    interactivity:
      feature: "State Dropdown"
      impact: "Allows for exploration of license types in different states."
  - title: Top 5 License Status Distribution by Cities
    type: pie_chart
    description: "This pie chart visualizes the distribution of the top 5 most frequent license statuses in cities."
    color_scheme: categorical
    data_transformation: 
      filter: "Cities with at least 5 license types"
      aggregate: "Top 5 License Statuses"
    interactivity:
      feature: "City Selection"
      impact: "Enables users to explore the license status distribution for selected cities."
footer: 
  text: "License Visualizations - Submitted by Ruchita Alate"
  contact: "ralate2@illinois.edu"
